twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/assets/dashboard-ui/authentication/assets/images': loginImages

when@test:
    twig:
        strict_variables: true
