version: '3.4'

networks:
  chess-tournaments-network:
    driver: bridge

services:
  chess-tournaments-nginx:
    container_name: chess-tournaments-nginx
    image: nginx:stable-alpine
    ports:
      - "${DOCKER_NGINX_PORT:-36500}:80"
    networks:
      - chess-tournaments-network
    volumes:
      - ./:/var/www/html
      - ./docker/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chess-tournaments-php
      - chess-tournaments-mysql

  chess-tournaments-php:
    build:
      context: .
      dockerfile: ./docker/etc/php/main.Dockerfile
    container_name: chess-tournaments-php
    ports:
      - "${DOCKER_PHP_PORT:-36501}:9000"
    networks:
      - chess-tournaments-network
    depends_on:
      - chess-tournaments-mysql
    volumes:
      - ./:/var/www/html

  chess-tournaments-mysql:
    container_name: chess-tournaments-mysql
    image: mysql:8.0
    networks:
      - chess-tournaments-network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DB}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${DOCKER_MYSQL_PORT:-36502}:3306"

  chess-tournaments-mysql-test:
    container_name: chess-tournaments-mysql-test
    image: mysql:8.0
    networks:
      - chess-tournaments-network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DB_TEST}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    ports:
      - "${DOCKER_MYSQL_TEST_PORT:-36503}:3306"

  chess-tournaments-node:
    container_name: chess-tournaments-node
    image: node:latest
    working_dir: /var/www/html
    networks:
      - chess-tournaments-network
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run watch"

  chess-tournaments-mailhog:
    image: mailhog/mailhog:latest
    container_name: chess-tournaments-mailhog
    platform: linux/amd64
    restart: on-failure
    ports:
      - '${DOCKER_MAILHOG_SMTP_PORT:-36504}:1025'
      - '${DOCKER_MAILHOG_HTTP_PORT:-36594}:8025'
    networks:
      - chess-tournaments-network

volumes:
    mysql-data:
