version: '3.4'

networks:
  chess-tournaments-network:
    driver: bridge

services:
  chess-tournaments-nginx:
    container_name: chess-tournaments-nginx
    image: nginx:stable-alpine
    ports:
      - "${DOCKER_NGINX_PORT:-36500}:80"
    networks:
      - chess-tournaments-network
    volumes:
      - ./:/var/www/html
      - ./docker/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chess-tournaments-php
      - chess-tournaments-mysql

  chess-tournaments-php:
    build:
      context: .
      dockerfile: ./docker/etc/php/main.Dockerfile
    container_name: chess-tournaments-php
    ports:
      - "${DOCKER_PHP_PORT:-36501}:9000"
    networks:
      - chess-tournaments-network
    depends_on:
      - chess-tournaments-mysql
    volumes:
      - ./:/var/www/html

  chess-tournaments-mysql:
    container_name: chess-tournaments-mysql
    image: mysql:8.0
    networks:
      - chess-tournaments-network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DB}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${DOCKER_MYSQL_PORT:-36502}:3306"

  chess-tournaments-mysql-test:
    container_name: chess-tournaments-mysql-test
    image: mysql:8.0
    networks:
      - chess-tournaments-network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DB_TEST}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    ports:
      - "${DOCKER_MYSQL_TEST_PORT:-36503}:3306"

  chess-tournaments-node:
    container_name: chess-tournaments-node
    image: node:latest
    working_dir: /var/www/html
    networks:
      - chess-tournaments-network
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run watch"

  chess-tournaments-mailhog:
    image: mailhog/mailhog:latest
    container_name: chess-tournaments-mailhog
    platform: linux/amd64
    restart: on-failure
    ports:
      - '${DOCKER_MAILHOG_SMTP_PORT:-36504}:1025'
      - '${DOCKER_MAILHOG_HTTP_PORT:-36594}:8025'
    networks:
      - chess-tournaments-network

  chess-tournaments-elasticsearch:
    container_name: chess-tournaments-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    platform: linux/amd64
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      xpack.security.enabled: ${ELASTICSEARCH_SECURITY}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - chess-tournaments-network

  chess-tournaments-logstash:
    container_name: chess-tournaments-logstash
    image: docker.elastic.co/logstash/logstash:7.4.2
    platform: linux/amd64
    depends_on:
      - chess-tournaments-elasticsearch
    volumes:
      - ./docker/etc/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:cached
      - ./docker/etc/logstash/conf.d:/etc/logstash/conf.d:cached
      - ./var/log:/var/www/chess-tournaments/log
    networks:
      - chess-tournaments-network

  chess-tournaments-kibana:
    container_name: chess-tournaments-kibana
    platform: linux/amd64
    depends_on:
      - chess-tournaments-elasticsearch
    image: docker.elastic.co/kibana/kibana:7.4.2
    environment:
      SERVER_NAME: localhost
#   TODO Uncomment this line when you have a domain name
#      SERVER_NAME: szachowymistrz.pl
      ELASTICSEARCH_HOSTS: http://chess-tournaments-elasticsearch:9200
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
    networks:
      - chess-tournaments-network
    ports:
      - "36505:5601"

volumes:
    mysql-data:
    esdata:
