server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://chess-tournament-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - "localhost"
#          - "szachowymistrz.pl" # TODO Uncomment this line to scrape logs for szachowymistrz.pl production server
        labels:
          job: varlogs
          __path__: /var/log/*log
  - job_name: symfony
    static_configs:
      - targets:
          - localhost
#          - "szachowymistrz.pl" # TODO Uncomment this line to scrape logs for szachowymistrz.pl production server
        labels:
          job: symfony
          __path__: /var/log/*.log