site_name: Chess tourmanents
docs_dir: ../../docs/en
site_dir: ../../site/en
nav:
  - Home: index.md
  - Tournaments:
    - "Tournament 1": tournament1.md
    - "Tournament 2": tournament2.md
    - "Tournament 3": tournament3.md
  - About: about.md
theme:
  direction: ltr
  language: en
  name: readthedocs
  palette:
      primary: green
      accent: blue
  font:
      text: "Roboto"
      code: "Roboto Mono"
  logo: "images/chess-master-logo.png"
  favicon: "images/chess-master-favicon.png"
plugins:
  - search:
      lang: en

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Polski
      link: /pl/
      lang: pl