site_name: Chess tourmanents
docs_dir: ../../docs/pl
site_dir: ../../site/pl
site_url: https://kkedzierski.github.io/chess-tournaments/pl/
nav:
  - Strona główna: index.md
  - O projekcie: about.md
  - Podręcznik użytkownika:
    - "Panel administratora": userGuide/administrationPanel.md
    - "Panel użytkownika": userGuide/userPanel.md
  - Podręcznik techniczny:
    - "Instalacja": technicalGuide/installation.md
    - "Konfiguracja": technicalGuide/configuration.md
    - "Dokumentacja API": technicalGuide/api.md
    - "Testy": technicalGuide/tests.md
    - "Wydanie": technicalGuide/release.md
theme:
  language: pl
  name: readthedocs
  palette:
      primary: green
      accent: blue
  font:
      text: "Roboto"
      code: "Roboto Mono"
  logo: "images/chess-master-logo.png"
  favicon: "images/chess-master-favicon.png"
plugins:
  - search:
      lang: pl

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Polski
      link: /pl/
      lang: pl