controllers_dashboard:
    resource:
        path: ../src/Dashboard/Ui/
        namespace: App\Dashboard\Ui
    type: attribute
controllers_account:
    resource:
        path: ../src/Account/Ui/
        namespace: App\Account\Ui
    type: attribute
controllers_tournament:
    resource:
        path: ../src/Tournament/Ui/
        namespace: App\Tournament\Ui
    type: attribute
controllers_company:
    resource:
        path: ../src/Company/Ui/
        namespace: App\Company\Ui
    type: attribute
translation_controller:
    resource:
        path: ../src/Kernel/Translator/
        namespace: App\Kernel\Translator
    type: attribute