site_name: Szachowymistrz.pl
docs_dir: ./docs
site_dir: ./site
site_url: https://kkedzierski.github.io/chess-tournaments/
nav:
  - Home: index.md
  - About: about.md
  - FAQ: faq.md
  - User quide:
      - "Administration panel": userGuide/administrationPanel.md
      - "User panel": userGuide/userPanel.md
  - Technical guide:
      - Installation: technicalGuide/installation.md
      - Running: technicalGuide/running.md
      - Api documentation: technicalGuide/api.md
      - Code documentation: technicalGuide/code.md
      - This documentation: technicalGuide/thisDocumentation.md
      - Tests: technicalGuide/tests.md
  - Authors: authors.md
theme:
  language: pl
  name: material
  palette:
      primary: green
      accent: blue
  font:
      text: "Roboto"
      code: "Roboto Mono"
#  logo: "./assets/images/chess-master-logo.png"
#  favicon: "./assets/images/chess-master-favicon.ico"
plugins:
  - search:
      lang: en
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pl
          name: Polski
          build: true
          default: true
          nav_translations:
            Home: Strona główna
            About: O projekcie
            FAQ: FAQ
            User quide: Podręcznik użytkownika
            Administration panel: Panel administratora
            User panel: Panel użytkownika
            Technical guide: Podręcznik techniczny
            Installation: Instalacja
            Running: Uruchamianie
            Api documentation: Dokumentacja API
            Code documentation: Dokumentacja kodu
            This documentation: Ta dokumentacja
            Tests: Testy
            Authors: Autorzy
