name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

#    services:
#      mysql:
#        image: mysql:8.0
#        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
#        env:
#          MYSQL_ROOT_PASSWORD: root
#          MYSQL_DATABASE: test_db
#        ports:
#          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up -d --build

#      - name: Wait for MySQL
#        run: |
#          until docker-compose exec mysql mysqladmin ping --silent; do
#            echo "Waiting for MySQL..."
#            sleep 5
#          done

      - name: Install PHP dependencies
        run: docker-compose exec php composer install

      - name: Run PHPUnit
        run: docker-compose exec php ./vendor/bin/phpunit --configuration phpunit.xml

      - name: Run PHPStan
        run: docker-compose exec php ./vendor/bin/phpstan analyse src --level max

      - name: Run PHPInfection
        run: docker-compose exec php ./vendor/bin/infection --min-msi=70 --min-covered-msi=80

      - name: Run PHPCS
        run: docker-compose exec php ./vendor/bin/phpcs --standard=PSR12 src

      - name: Shutdown Docker Compose
        run: docker-compose down
