name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
# TODO add behat tests
#    services:
#      mysql:
#        image: mysql:8.0
#        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
#        env:
#          MYSQL_ROOT_PASSWORD: root
#          MYSQL_DATABASE: test_db
#        ports:
#          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls -la

      - name: Build Docker image
        run: docker build -t chess-tournaments-php -f ./docker/etc/php/main.Dockerfile .

      - name: Set up Docker Compose
        run: docker-compose up -d

#      TODO add behat tests
#      - name: Wait for MySQL
#        run: |
#          until docker-compose exec mysql mysqladmin ping --silent; do
#            echo "Waiting for MySQL..."
#            sleep 5
#          done
#
      - name: Install PHP dependencies
        run: docker-compose exec -T chess-tournaments-php composer install --no-scripts

      - name: Run PHPUnit
        run: docker-compose exec -T chess-tournaments-php ./vendor/bin/phpunit --configuration phpunit.xml.dist

      - name: Run grumphp (composer, phpcsfixer, phpstan, infection)
        run: docker-compose exec -T chess-tournaments-php ./vendor/bin/grumphp run

      - name: Shutdown Docker Compose
        run: docker-compose down
